#!/usr/bin/env python
# encoding: utf-8
"""
allow.py

Created by Thomas Mangin on 2011-11-29.
Copyright (c) 2011 Exa Networks. All rights reserved.
"""

# redirect.php is a simple to force hostname :
# <?php 
# header('HTTP/1.1 301 Moved Permanently');
# header( 'Location: http://www.surfprotect.co.uk/' ) ; ?>
# ?>

import sys

try:
	while True:
		version = sys.stdin.readline()
		if version.strip() != 'version:1':
			sys.exit(0)
		client = sys.stdin.readline()
		if not client.strip().startswith('client:'):
			sys.exit(0)
		size = int(sys.stdin.readline().strip()[5:])
		_ = sys.stdin.read(size)

		if _[:7].upper() == 'CONNECT':
			headers = _ if 'exa-networks.co.uk' in _ else """\
CONNECT www.exa-networks.co.uk:443 HTTP/1.1
Proxy-Connection: keep-alive
Host: www.exa-networks.co.uk

"""
		else:
			headers = _ if 'surfprotect.co.uk' in _ else """\
GET /redirect.php HTTP/1.1
Host: www.surfprotect.co.uk
Connection: close

"""
		print >> sys.stderr, "BEFORE", _ 
		print >> sys.stderr, "AFTER ", headers
		sys.stdout.write('%d\n' % len(headers))
		sys.stdout.flush()
		sys.stdout.write('%s' % headers)
		sys.stdout.flush()
except KeyboardInterrupt, e:
	sys.stderr.write('^C keyboard interrupt. exiting.\n')
	sys.stderr.flush()
except Exception, e:
	sys.stderr.write('CHILD FAILED %s\n' % str(e))
	sys.stderr.flush()
