#!/usr/bin/env python
# encoding: utf-8
"""
allow.py

Created by Thomas Mangin on 2011-11-29.
Copyright (c) 2011 Exa Networks. All rights reserved.
"""

import sys

try:
	while True:
		version = sys.stdin.readline()
		if version.strip() != 'version:1':
			sys.exit(0)
		client = sys.stdin.readline()
		if not client.strip().startswith('client:'):
			sys.exit(0)
		size = int(sys.stdin.readline().strip()[5:])
		headers = sys.stdin.read(size)
		sys.stdout.write('%d\n' % len(headers))
		sys.stdout.flush()
		sys.stdout.write('%s' % headers)
		sys.stdout.flush()
except KeyboardInterrupt, e:
	sys.stderr.write('^C keyboard interrupt. exiting.\n')
	sys.stderr.flush()
except Exception, e:
	sys.stderr.write('CHILD FAILED %s\n' % str(e))
	sys.stderr.flush()
