#!/usr/bin/env python
# encoding: utf-8
"""
allow.py

Created by Thomas Mangin on 2011-11-29.
Copyright (c) 2011 Exa Networks. All rights reserved.
"""

# redirect.php is a simple to force hostname :
# <?php 
# header('HTTP/1.1 301 Moved Permanently');
# header( 'Location: http://www.surfprotect.co.uk/' ) ; ?>
# ?>

import re
import sys

try:
	while True:
		version = sys.stdin.readline()
		if version.strip() != 'version:1':
			sys.exit(0)
		client = sys.stdin.readline()
		if not client.strip().startswith('client:'):
			sys.exit(0)
		size = int(sys.stdin.readline().strip()[5:])
		_ = sys.stdin.read(size)
		upper = _.upper()

		if 'CONNECT ' in upper:
			#print >> sys.stderr, 'CONNECT'
			headers = _ 
		elif 'youtube.' in _:
			#print >> sys.stderr, "BEFORE", len(_),'\n',  _ 
			headers = re.sub("([Cc]ookie:.*)PREF=([^;]*)(.*)","\\1PREF=f2=8000000&\\2; \\3",_)
			#print >> sys.stderr, "AFTER ", len(headers), '\n', headers
		else:
			#print >> sys.stderr, 'PASS'
			headers = _

		sys.stdout.write('%d\n' % len(headers))
		sys.stdout.flush()
		sys.stdout.write('%s' % headers)
		sys.stdout.flush()
except KeyboardInterrupt, e:
	sys.stderr.write('^C keyboard interrupt. exiting.\n')
	sys.stderr.flush()
except Exception, e:
	sys.stderr.write('CHILD FAILED %s\n' % str(e))
	sys.stderr.flush()

