#!/usr/bin/env python
# encoding: utf-8
"""
parrot.py

Created by Thomas Mangin on 2011-11-29.
Copyright (c) 2011 Exa Networks. All rights reserved.
"""

import sys

try:
	while True:
		data = sys.stdin.readline()
		url = data.split(' ')[0]
		sys.stdout.write('%s\r\n' % url)
		sys.stdout.flush()
except KeyboardInterrupt, e:
	sys.stderr.write('^C keyboard interrupt. exiting.\n')
	sys.stderr.flush()
except Exception, e:
	sys.stderr.write('CHILD FAILED %s\n' % str(e))
	sys.stderr.flush()
