#!/bin/bash

dirname=`dirname $0`

if [[ $dirname == /* ]]; then
        path=$dirname/..
else
        cd `pwd`/$dirname/.. > /dev/null
        path=`pwd`
        cd - > /dev/null
fi

export PYTHONPATH=$path/lib:/usr/share/exaproxy/lib/1.0.0
export ETC=$path/etc/exaproxy

PYPY=`which python2.6`
PYTHON27=`which python2.7`
PYTHON26=`which python2.6`
PYTHON25=`which python2.5`
PYTHON24=`which python2.4`
PYTHON2=`which python2`
PYTHON=`which python`

if [ -f "$PYPY" ]
then
  INTERPRETER=$PYPY
elif [ -f "$PYTHON27" ]
then
  INTERPRETER=$PYTHON27
elif [ -f "$PYTHON26" ]
then
  INTERPRETER=$PYTHON26
elif [ -f "$PYTHON25" ]
then
  INTERPRETER=$PYTHON25
elif [ -f "$PYTHON24" ]
then
  INTERPRETER=$PYTHON24
elif [ -f "$PYTHON2" ]
then
  INTERPRETER=$PYTHON2
elif [ -f "$PYTHON" ]
then
  INTERPRETER=$PYTHON
else
  INTERPRETER=python
fi

if [ -d "$path/etc/content" ]
then
	export CONTENT=$path/etc/content
fi

APPLICATIONS=`$INTERPRETER -c "import sys,os; print ' '.join(os.path.join(_,'exaproxy','application.py') for _ in sys.path if os.path.isfile('/'.join((_,'exaproxy/application.py'))))"`
APPLICATION=`echo $APPLICATIONS | awk '{ print $1; }'`

exec $INTERPRETER -m exaproxy.util.debug $APPLICATION $*
