#!/bin/bash

dirname=`dirname $0`

if [[ $dirname == /* ]]; then
        path=$dirname/..
else
        cd `pwd`/$dirname/.. > /dev/null
        path=`pwd`
        cd - > /dev/null
fi

export PYTHONPATH=$path/lib
export ETC=$path/etc/exaproxy

PYTHON=`which python`
PYPY=`which pypy`

if [ -f "$PYPY" ]
then
	INTERPRETER=$PYTHON
	INTERPRETER=$PYTHON
elif [ -f "$PYTHON" ]
then
	INTERPRETER=$PYTHON
else
	INTERPRETER=python
fi

if [ -d "$path/etc/content" ]
then
	export CONTENT=$path/etc/content
fi

$INTERPRETER -m exaproxy.util.debug $path/lib/exaproxy/application.py $*
