#!/bin/sh

dirname=`dirname $0`

case $dirname in
/*)
        path=$dirname/../..
        ;;
*)
        cd `pwd`/$dirname/../.. > /dev/null
        path=`pwd`
        cd - > /dev/null
        ;;
esac

exec env PYTHONPATH=$path/lib $path/sbin/exaproxy 2>&1
